In [1]:
import numpy as np

In [2]:
# Exercise 1: 
# How to replace items that satisfy a condition with another value in numpy array?(2 Points) Replace all odd numbers in arr with -1
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [3]:
# Exercise 2: 
# How to reshape an array?(2 Points)
# Convert a 1D array to a 2D array with 2 rows
# arr = np.arange(10)
# Desired Output:([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

arr = np.arange(10)
np.reshape(arr,(2,5))  #https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
# Exercise 3: 
# How to generate custom sequences in numpy without hardcoding?(2 Points) 
# Create the following pattern without hardcoding. Use only numpy functions and the below input array
# arr = np.array([1,2,3])
# Desired Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

arr = np.array([1,2,3])

# 2 independent operations
arr1 = np.repeat(arr,3) # array([1, 1, 1, 2, 2, 2, 3, 3, 3]) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html
#arr1 = np.column_stack((arr1,arr1,arr1)).flatten() # array([1, 1, 1, 2, 2, 2, 3, 3, 3])
arr2 = np.repeat([arr],3, axis=0).flatten() # array([1, 2, 3, 1, 2, 3, 1, 2, 3])

# appending to 1 array
arr3 = np.append(arr1,arr2)
arr3

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [5]:
# Exercise 4: 
# How to get the common items between two python numpy arrays?(2 Points) Get the common items between a and b
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:(array([2, 4]))

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# https://stackoverflow.com/questions/40903518/match-two-numpy-arrays-to-find-the-same-elements
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.in1d.html
# Test whether each element of a 1-D array is also present in a second array

match = a[np.in1d(a,b)]
np.unique(match)

array([2, 4])

In [6]:
# Exercise 5:
# How to get the positions where elements of two arrays match?(2 Points) Get the positions where elements of a and b match
# a = np.array((1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:(array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(np.in1d(a,b)) # https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html


(array([1, 3, 5, 7], dtype=int64),)

In [7]:
# Exercise 6: 
# How to create a 2D array containing random floats between 5 and 10?(2 Points)
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

np.random.uniform(5,10,15).reshape(5,3) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html

array([[6.03733396, 9.3685336 , 7.03138265],
       [9.49778393, 9.09449506, 6.11389822],
       [6.90954375, 6.82532881, 8.54850079],
       [8.88869412, 8.76444888, 9.66878534],
       [5.1086146 , 9.93126968, 5.21448261]])

In [8]:
# Exercise 7:
# How to limit the number of items printed in output of numpy array to 6?(2 Points)
# Limit the number of items printed in python numpy array a to a maximum of 6 elements.
# arr = np.arange(15)
# Desired Output:array([ 0, 1, 2, ..., 12, 13, 14])

np.set_printoptions(threshold=6) # https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.set_printoptions.html
arr = np.arange(15)
arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [9]:
# Exercise 8:
# How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?(2 Points)
# Limit the number of items printed in python numpy array a to a maximum of 6 elements. 
# np.random.seed(100) rand_arr = np.random.random([3,3])/1e3
# Desired Output:array([[ 0.000543, 0.000278, 0.000425], | 0.000845, 0.000005, 0.000122], [ 0.000671, 0.000826, 0.000137]])

np.set_printoptions(suppress=True) # https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.set_printoptions.html
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.00078772, 0.00030495, 0.00010377],
       [0.00099396, 0.00063592, 0.0007474 ],
       [0.00012286, 0.00099394, 0.00086861]])

In [10]:
# Exercise 9: 
# How to swap two columns in a 2d numpy array?(2 Points) Swap columns 1 and 2 in the array arr.
# arr = np.arange(9).reshape(3,3)

arr = np.arange(9).reshape(3,3)
arr1 = arr.copy()
print(arr)
print("\nswapped columns 1 and 2 array is: \n")
arr1[:, 0] = arr1[:, 1] 
arr1[:, 1] = arr[:, 0]
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

swapped columns 1 and 2 array is: 

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [11]:
# Exercise 10: 
# How to swap two rows in a 2d numpy array?(2 Points)
# Swap rows 1 and 2 in the array arr:
# arr = np.arange(9).reshape(3,3) 

arr = np.arange(9).reshape(3,3) 
arr1 = arr.copy()
print(arr)
print("\nswapped rows 1 and 2 array is: \n")
arr1[0, :] = arr1[1, :] 
arr1[1, :] = arr[0, :]
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

swapped rows 1 and 2 array is: 

[[3 4 5]
 [0 1 2]
 [6 7 8]]
